name: Build SubMin.yaml

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 👇 就是这一行，授权写入权限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: 下载远程订阅到 proxies-by-one.yaml
        run: |
          # 读取providers-by-one.yaml中的url，去除换行空格
          URL=$(cat providers-by-one.yaml | tr -d '\r\n ')
          echo "Fetch url: $URL"
          # curl下载，输出到 proxies-by-one.yaml
          curl -sL --connect-timeout 15 "$URL" -o proxies-by-one.yaml

      - name: 下载远程订阅到 proxies-by-two.yaml（如果你也需要，同理）
        run: |
          URL2=$(cat providers-by-two.yaml | tr -d '\r\n ')
          echo "Fetch url2: $URL2"
          curl -sL --connect-timeout 15 "$URL2" -o proxies-by-two.yaml
      
      - name: 合并生成 SubMin.yaml
        run: |
          # 获取配置

          # 写入head.yaml全部内容
          cat head.yaml > SubMin.yaml

          # proxies‑by‑one.yaml 跳过第一行追加
          cat proxies-by-one.yaml >> SubMin.yaml

          # proxies‑by‑two.yaml 跳过第一行追加
          tail -n +2 proxies-by-two.yaml >> SubMin.yaml

          # proxy-groups.yaml 放入 SubMin.yaml
          cat proxy-groups.yaml >> SubMin.yaml

      - name: 自动提交回去
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: "机器自动搓的，别找我"

